### ISSUE TITLE
When reloading the page, there will be a flash of black color thingy in the UI

### ISSUE THREAD

**Issue by lyeyixian** [lyeyixian/acfirst-ordering#1]
- no matter in dark or light mode

https://github.com/lyeyixian/acfirst-ordering/assets/58477697/f4ff97c7-9eeb-4d90-8e02-a54115aced1c

**Comment by jiaweiteo** [comment]
hmm, I dont have this issue on my windows laptop. Only the stocks overview/order history blue bar will change to black when refreshed.
