### ISSUE TITLE
Update worker to follow the latest schema

### ISSUE THREAD

**Issue by lyeyixian** [lyeyixian/acfirst-ordering#2]
- only need to listen to `Events` collection
- logic:
  - update `status` to `processing`
  - process the events (SQL Acc stuff)
  - update `status` to `completed` or `failed` after processing and updated firestore

**schema:**

```json
{
  "id": "firebase-id",
  "type": "refreshStocks | createInvoice | createDeliveryOrder",
  "payload": {
    "code": "string",
    "data": [
      {
        "itemCode": "string",
        "qty": "number"
      }
    ]
  },
  "status": "queued | processing | completed | failed",
  "createdBy": "userId",
  "createdAt": "timestamp",
  "updatedAt": "timestamp"
}
```

**Comment by jiaweiteo** [comment]
Have to captizalise all fields in "payload": Data, Code, ItemCode, Qty, Description (If application) for SQLAccounting to register its value.
