### ISSUE TITLE
User will be able to select multiple items from stocks table and add to cart

### ISSUE THREAD

**Issue by lyeyixian** [lyeyixian/acfirst-ordering#5]
- add tickbox to grid for user to select multiple items
- add button which opens up a modal where the user will be able to choose the quantity for each item selected
  - then add to cart button in the modal
- they will be able to see the total price
- need to check quantity not exceed current stock

**Comment by jiaweiteo** [comment]
1. Update quantity value to a set,
2. Create hook/form to link frontend data to backend api
