### ISSUE TITLE
Create dropdown list for company names during user creation

### ISSUE THREAD

**Issue by jiaweiteo** [lyeyixian/acfirst-ordering#9]
When creating sales invoice/delivery order, a company code is needed for SQL Accounting to tag the order to the code. On the frontend, we need to either pass the exact companyname or the code to the firebase collection so that our listener can retrieve it can create the sales invoice/delivery order.

Proposed solution: On user sign up, we have a drop down list for user to choose which company they are from. This will be retrieved from firebase which will be from SQL Accounting. One of the cons for this will be that any user will know which companies are purchasing from AC-First. To be discussed.

1. Create getCompanyNames() in worker. 
2. Store all company names and code and store it in firebase collection: "Companies"
3. On frontend, retrieve company names from firebase and put it in dropdown list.

**Comment by lyeyixian** [comment]
- ACFIRST TILES& SANITARYWARES 
3000-A003
- ACFIRST CERAMIC CENTRE 
3000-A002
- AC FIRST TILES TRADING
3000-A004
- PUSAT JUBIN KANGAR SDN BHD
3000-P001
